### ISSUE TITLE
Correct method for passing "orderBy:" as a variable?

### ISSUE THREAD

**Issue by Trellian** [Vincit/objection-graphql#23]
I'm trying to pass in the "orderBy:" parameter as a variable in the GraphiQL client, but I'm not sure how:

```
query getRegions ($order: String) {
  iwRegions (range: [0, 4], orderBy: $order) {
    name
  }
}
```
with variables:
```
{
  "order": "name"
}
```
but I get an error message:
```
{
  "errors": [
    {
      "message": "Variable \"$order\" of type \"String\" used in position expecting type \"IwRegionPropertiesEnum\".",
      "locations": [
        {
          "line": 1,
          "column": 19
        },
        {
          "line": 2,
          "column": 38
        }
      ]
    }
  ]
}
```
How should I do this?

Thanks,
Adrian

**Comment by koskimas** [comment]
Maybe this https://stackoverflow.com/questions/35946313/how-to-set-a-relay-variable-as-an-enum-value/35987582#35987582 ?

**Comment by koskimas** [comment]
Does this work?

```js
query getRegions ($order: IwRegionPropertiesEnum) {
  iwRegions (range: [0, 4], orderBy: $order) {
    name
  }
}
```

**Comment by Trellian** [comment]
I can't get it to work, but... GraphiQL is doing something odd. When I paste the above (with a few extra columns included in the query), and then try to set up the variables, the typeahead functionality in the variables pane forces the following:
```
{
  "order": "name"
}
or similar, for the other column names (if I add them to the query). 

Executing the query then produces:
```
{
  "data": {
    "iwRegions": null
  },
  "errors": [
    {
      "message": "undefined passed as argument #0 for 'orderBy' operation. Call skipUndefined() method to ignore the undefined values.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "iwRegions"
      ]
    }
  ]
}
```

**Comment by Trellian** [comment]
Note the line number at "node_modules\objection-graphql\lib\argFactories.js:119:15" should be 118, but I stuck a 'console.warn()' in at 118

**Comment by koskimas** [comment]
@Trellian I found a bug in this. It's now fixed in master

**Comment by Trellian** [comment]
Awesome! Thank you!
