### ISSUE TITLE
graphql latest version support 

### ISSUE THREAD

**Issue by nasushkov** [Vincit/objection-graphql#4]
Hi 
I encounter a problem using this package with the latest version of graphql js (0.9.2 in my case). The problem is in _resolverForModel: it looks like fieldASTs is not there anymore, so I've got an error  "using [0] with undefined"

**Comment by nasushkov** [comment]
Thanx!

**Comment by koskimas** [comment]
You're welcome! I released 0.1.2 with the fix.
