### ISSUE TITLE
GraphQL query params and "OR" support

### ISSUE THREAD

**Issue by nasushkov** [Vincit/objection-graphql#5]
Hi
I am playing around this project for a while and I stuck with two problems right now:

1. I want to use parameters for my queries, but they don't work for me for some reason. For instance, this query retrieves an empty set:

```
query getEnAirports($part:String){
  airports(iataLike: $part){
    id,
    name,    
    city,
    country,
    iata
  }
}

{
  "part": "%PE%"
}
```

while the same query with a hard coded value does the job:

```
query getEnAirports{
  airports(iataLike: "%PE%"){
    id,
    name,    
    city,
    country,
    iata
  }
}
```
   
2. The second problem is "OR" support for queries. What's the right way to implement this? Should it be implemented as it is described in "Adding your own custom arguments" section with a custom suffix or there is another more convenient way?

Thanks.

**Comment by koskimas** [comment]
Parameters are not supported I'm afraid. I'm not aware of an easier way to do `OR` but to add custom args like `iataLikeOr`. Even then grouping won't be possible because there are no way to implement parentheses.

This project is not actively maintained at the moment. I'm the only developer and I've got my hands full with objection.js.

**Comment by nasushkov** [comment]
@koskimas Thanks for your reply. Ok, maybe I'll try to look at this by myself. BTW I like _objection.js_ and I think it's the best Node.js ORM out there  (well for my taste and needs) and also as GraphQL is gaining a great momentum now,  this project is undeservedly abandoned.

**Comment by koskimas** [comment]
Yeah, there just isn't enough hours in a day...
