### ISSUE TITLE
Npm probably not updated virtual attributes to 0.4.1

### ISSUE THREAD

**Issue by pavellob** [Vincit/objection-graphql#58]
Hi.
Npm not updated to 0.4.1 with virtual attributes:
I saw old implimentation in my SchemaBuilder
:
`virtualJsonSchemaProperties: modelData.modelClass.virtualJsonSchemaProperties`
and 0.4.1 in package.json

I get it from my package-lock.json:
https://registry.npmjs.org/objection-graphql/-/objection-graphql-0.4.1.tgz
how can you see - old version here.
Thanks.

**Comment by timhuff** [comment]
It looks like I didn't pull before publishing 0.4.1. Thanks for pointing this out to me. I just published 0.4.2, which should resolve this issue.
